package gui_calculadora;

public class Calculadora_Gui extends javax.swing.JFrame {
    int num1Int = 0, num2Int = 0, resultado = 0;
    String op = "";

    public Calculadora_Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jBotao1 = new javax.swing.JButton();
        jBotao2 = new javax.swing.JButton();
        jBotao3 = new javax.swing.JButton();
        jBotao4 = new javax.swing.JButton();
        jBotao5 = new javax.swing.JButton();
        jBotao6 = new javax.swing.JButton();
        jBotao7 = new javax.swing.JButton();
        jBotao8 = new javax.swing.JButton();
        jBotao9 = new javax.swing.JButton();
        jBotao0 = new javax.swing.JButton();
        jButtonSoma = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        visor = new javax.swing.JTextField();
        jButtoIgual = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton14.setText("jButton14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jBotao1.setText("1");
        jBotao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao1ActionPerformed(evt);
            }
        });

        jBotao2.setText("2");
        jBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao2ActionPerformed(evt);
            }
        });

        jBotao3.setText("3");
        jBotao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao3ActionPerformed(evt);
            }
        });

        jBotao4.setText("4");
        jBotao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao4ActionPerformed(evt);
            }
        });

        jBotao5.setText("5");
        jBotao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao5ActionPerformed(evt);
            }
        });

        jBotao6.setText("6");
        jBotao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao6ActionPerformed(evt);
            }
        });

        jBotao7.setText("7");
        jBotao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao7ActionPerformed(evt);
            }
        });

        jBotao8.setText("8");
        jBotao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao8ActionPerformed(evt);
            }
        });

        jBotao9.setText("9");
        jBotao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao9ActionPerformed(evt);
            }
        });

        jBotao0.setText("0");
        jBotao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao0ActionPerformed(evt);
            }
        });

        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jButtonMenos.setText(" -");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });

        jButtoIgual.setText("=");
        jButtoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBotao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotao3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSoma))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotao5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBotao0)
                                    .addComponent(jBotao8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBotao6)
                            .addComponent(jBotao9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMenos)
                            .addComponent(jButtoIgual))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotao1)
                    .addComponent(jBotao2)
                    .addComponent(jBotao3)
                    .addComponent(jButtonSoma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotao4)
                    .addComponent(jBotao5)
                    .addComponent(jBotao6)
                    .addComponent(jButtonMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotao7)
                    .addComponent(jBotao9)
                    .addComponent(jBotao8)
                    .addComponent(jButtoIgual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotao0)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao1ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "1");
    }//GEN-LAST:event_jBotao1ActionPerformed

    private void jBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao2ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "2");
    }//GEN-LAST:event_jBotao2ActionPerformed

    private void jBotao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao6ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "6");
    }//GEN-LAST:event_jBotao6ActionPerformed

    private void jBotao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao7ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "7");
    }//GEN-LAST:event_jBotao7ActionPerformed

    private void jBotao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao4ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "4");
    }//GEN-LAST:event_jBotao4ActionPerformed

    private void jBotao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao9ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "9");
    }//GEN-LAST:event_jBotao9ActionPerformed

    private void jBotao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao3ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "3");
    }//GEN-LAST:event_jBotao3ActionPerformed

    private void jBotao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao5ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "5");
    }//GEN-LAST:event_jBotao5ActionPerformed

    private void jBotao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao8ActionPerformed
        String dado = visor.getText();
        visor.setText(dado + "8");
    }//GEN-LAST:event_jBotao8ActionPerformed

    private void jBotao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao0ActionPerformed
        // TODO add your handling code here:
        String dado = visor.getText();
        visor.setText(dado + "");
    }//GEN-LAST:event_jBotao0ActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        // TODO add your handling code here:
        String num1Str = visor.getText();
        num1Int = Integer.parseInt(num1Str);
        
        op = "+";
        visor.setText("");
        System.out.println("o primeiro número é: " +
                num1Int + " e a operação foi " +
                op);
    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
        String num2Str = visor.getText();
        num2Int = Integer.parseInt(num2Str);
        
        op = "-";
        visor.setText("");
        System.out.println("o primeiro número é: " +
                num1Int + " e a operação foi " +
                op);
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed

    private void jButtoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoIgualActionPerformed
        String num2Str = visor.getText();
        int num2Int = Integer.parseInt(num2Str);
        
        switch (op) {
            case "+":
                resultado = num1Int + num2Int;
                break;
            case "-":
                resultado = num1Int - num2Int;
                break;
        }
        visor.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jButtoIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotao0;
    private javax.swing.JButton jBotao1;
    private javax.swing.JButton jBotao2;
    private javax.swing.JButton jBotao3;
    private javax.swing.JButton jBotao4;
    private javax.swing.JButton jBotao5;
    private javax.swing.JButton jBotao6;
    private javax.swing.JButton jBotao7;
    private javax.swing.JButton jBotao8;
    private javax.swing.JButton jBotao9;
    private javax.swing.JButton jButtoIgual;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
